### ISSUE TITLE
How to run inference on my own video/data

### ISSUE THREAD

**Issue by erictan23** [bar371/GEFF#11]
Hello @bar371 ! Thank you for the hardwork and sharing of your code. I would like to know how we can run the script on our own video data.

**Comment by bar371** [comment]
Hi @erictan23 . thank you for the interest in our work. 
We do not support inference directly from a video in this repository. In order to run the script on a video you will first need to pre-preprocess the video and create person crops using a person detector (for Image-based models), or tracker (to create tracklets).
Following that and in order to run your custom data with our work, we recommend conforming to the same structure and naming convention of the supported data formats (see LTCC for image based and 42Street for track-based).
